services:
  - type: web
    name: gnex-tts-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: your_bot_token_here
      - key: PORT
        value: 10000